dataset: imagenet100

model: afc

convnet: resnet18_importance
convnet_config:
  nf: 64

batch_size: 128

eval_type: cnn

classifier_config:
  type: cosine
  proxy_per_class: 10
  distance: neg_stable_cosine_distance

postprocessor_config:
  type: learned_scaling
  initial_value: 1.0

feature_distil:
  scheduled_factor: 10.0
  collapse_channels: pixel

nca:
  margin: 0.6
  scale: 1.
  exclude_pos_denominator: true

groupwise_factors:
  old_weights: 0.

finetuning_config:
  sampling: undersampling
  tuning: classifier
  lr: 0.02
  epochs: 20
  scaling: null

# Cosine Scheduling (CS)
scheduling: cosine

# Misc
epochs: 90
lr: 0.10
lr_decay: 0.1
optimizer: sgd
proxy_per_class: 1
weight_decay: 0.0001

weight_generation:
  type: imprinted
  multi_class_diff: kmeans

dataset_transforms:
  color_jitter: true
