dataset: cifar100

model: afc
convnet: rebuffi_importance

eval_type: nme
update_type: cnn

classifier_config:
  type: cosine
  scaling: 3.0
  proxy_per_class: 10
  distance: neg_stable_cosine_distance

feature_distil:
  scheduled_factor: 4.0
  collapse_channels: pixel

nca:
  margin: 0.6
  scale: 1.
  exclude_pos_denominator: true

groupwise_factors:
  old_weights: 0.

finetuning_config:
  sampling: undersampling
  tuning: classifier
  lr: 0.05
  epochs: 20
  scaling: null

# Cosine Scheduling (CS)
scheduling: cosine

# Misc
epochs: 160
lr: 0.1
lr_decay: 0.1
optimizer: sgd
proxy_per_class: 1
weight_decay: 0.0005

weight_generation:
  type: imprinted
  multi_class_diff: kmeans

dataset_transforms:
  color_jitter: true
